#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

setup_data_dir "${testname}"

error=0

${CARDANO_CLI} shelley address build \
    --testnet-magic 14 \
    --payment-verification-key-file "${DATA_DIR}/payment.vkey" \
    --staking-verification-key-file "${DATA_DIR}/staking.vkey" \
    > "${TEST_DIR}/staking-address.hex"
fail_on_error $?

assert_file_exists "${TEST_DIR}/staking-address.hex"
assert_line_count 1 "${TEST_DIR}/staking-address.hex"

${CARDANO_CLI} shelley address build \
    --testnet-magic 15 \
    --payment-verification-key-file "${DATA_DIR}/payment.vkey" \
    > "${TEST_DIR}/enterprise-address.hex"
fail_on_error $?

assert_file_exists "${TEST_DIR}/enterprise-address.hex"
assert_line_count 1 "${TEST_DIR}/enterprise-address.hex"

report_result ${error}
