#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

${CARDANO_CLI} shelley node key-gen-VRF \
    --verification-key-file "${TEST_DIR}/vrf.vkey" \
    --signing-key-file "${TEST_DIR}/vrf.skey"

assert_file_exists "${TEST_DIR}/vrf.vkey"
assert_file_exists "${TEST_DIR}/vrf.skey"

assert_string 'VerKeyVRF SimpleVRF' "${TEST_DIR}/vrf.vkey"
assert_string 'SignKeyVRF SimpleVRF' "${TEST_DIR}/vrf.skey"


report_result ${error}
