[inet_http_server]
port=127.0.0.1:9001

[program:generator]
autorestart=false
autostart=false
command=/nix/store/yisa2lg79zcvgk4ck4yr6r0lz6j63hs3-bash-interactive-5.3p9/bin/bash -c ':> ./exit_code; ./start.sh; exit_code="''$?"; echo "''$exit_code" > ./exit_code; exit "''$exit_code"'
directory=run/current/generator
killasgroup=true
startretries=0
startsecs=5
stderr_logfile=run/current/generator/stderr
stderr_logfile_maxbytes=0
stdout_logfile=run/current/generator/stdout
stdout_logfile_maxbytes=0
stopasgroup=true

[program:healthcheck]
autorestart=false
autostart=false
command=/nix/store/yisa2lg79zcvgk4ck4yr6r0lz6j63hs3-bash-interactive-5.3p9/bin/bash -c ':> ./exit_code; ./start.sh; exit_code="''$?"; echo "''$exit_code" > ./exit_code; exit "''$exit_code"'
directory=run/current/healthcheck
killasgroup=true
startretries=0
startsecs=5
stderr_logfile=run/current/healthcheck/stderr
stderr_logfile_maxbytes=0
stdout_logfile=run/current/healthcheck/stdout
stdout_logfile_maxbytes=0
stopasgroup=true

[program:node-0]
autorestart=false
autostart=false
command=/nix/store/yisa2lg79zcvgk4ck4yr6r0lz6j63hs3-bash-interactive-5.3p9/bin/bash -c ':> ./exit_code; ./start.sh; exit_code="''$?"; echo "''$exit_code" > ./exit_code; exit "''$exit_code"'
directory=run/current/node-0
killasgroup=true
startretries=0
startsecs=11
stderr_logfile=run/current/node-0/stderr
stderr_logfile_maxbytes=0
stdout_logfile=run/current/node-0/stdout
stdout_logfile_maxbytes=0
stopasgroup=true
stopwaitsecs=300

[program:node-1]
autorestart=false
autostart=false
command=/nix/store/yisa2lg79zcvgk4ck4yr6r0lz6j63hs3-bash-interactive-5.3p9/bin/bash -c ':> ./exit_code; ./start.sh; exit_code="''$?"; echo "''$exit_code" > ./exit_code; exit "''$exit_code"'
directory=run/current/node-1
killasgroup=true
startretries=0
startsecs=11
stderr_logfile=run/current/node-1/stderr
stderr_logfile_maxbytes=0
stdout_logfile=run/current/node-1/stdout
stdout_logfile_maxbytes=0
stopasgroup=true
stopwaitsecs=300

[program:tracer]
autorestart=false
autostart=false
command=/nix/store/yisa2lg79zcvgk4ck4yr6r0lz6j63hs3-bash-interactive-5.3p9/bin/bash -c ':> ./exit_code; ./start.sh; exit_code="''$?"; echo "''$exit_code" > ./exit_code; exit "''$exit_code"'
directory=run/current/tracer
killasgroup=true
startretries=0
startsecs=5
stderr_logfile=run/current/tracer/stderr
stderr_logfile_maxbytes=0
stdout_logfile=run/current/tracer/stdout
stdout_logfile_maxbytes=0
stopasgroup=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]

[supervisord]
logfile=run/current/supervisor/supervisord.log
pidfile=run/current/supervisor/supervisord.pid
strip_ansi=true
