#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

OUTPUT_DIR="${TEST}"

rm -rf "${OUTPUT_DIR}"
mkdir "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}/delegate-keys/" "${OUTPUT_DIR}/genesis-keys/"
cp "${cwd}/data/genesis.spec.json" "${OUTPUT_DIR}/"

error=0

${CARDANO_CLI} shelley genesis create-genesis \
    --genesis-dir "${OUTPUT_DIR}" \
    --genesis-delegates 1 \
    --supply 1000 > /dev/null

${CARDANO_CLI} shelley node key-gen-KES \
	--verification-key-file "${OUTPUT_DIR}/node-kes.vkey" \
    --signing-key-file "${OUTPUT_DIR}/node-kes.skey" \
    --kes-duration 100

${CARDANO_CLI} shelley node issue-op-cert \
    --hot-kes-verification-key-file "${OUTPUT_DIR}/node-kes.vkey" \
    --cold-signing-key-file "${OUTPUT_DIR}/delegate-keys/delegate1.skey" \
    --operational-certificate-issue-counter "${OUTPUT_DIR}/delegate-keys/delegate-opcert1.counter" \
    --kes-period 0 \
    --out-file "${OUTPUT_DIR}/operational.cert"

assert_file_exists "${OUTPUT_DIR}/operational.cert"

assert_string 'Node operational certificate' "${OUTPUT_DIR}/operational.cert"

report_result ${error}
