#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

${CARDANO_CLI} shelley genesis key-gen-genesis \
    --verification-key-file "${TEST_DIR}/key-gen.vkey" \
    --signing-key-file "${TEST_DIR}/key-gen.skey"

assert_file_exists "${TEST_DIR}/key-gen.vkey"
assert_file_exists "${TEST_DIR}/key-gen.skey"

assert_string 'GenesisVerificationKey_ed25519' "${TEST_DIR}/key-gen.vkey"
assert_string 'GenesisSigningKey_ed25519' "${TEST_DIR}/key-gen.skey"

report_result ${error}
