# Options for the trace forwarder
################################################################################
# Mainnet Cardano Node Configuration

##### Locations #####

AlonzoGenesisFile: mainnet-alonzo-genesis.json
AlonzoGenesisHash: 7e94a15f55d1e82d10f09203fa1d40f8eede58fd8066542cf6566008068ed874
ByronGenesisFile: mainnet-byron-genesis.json
ByronGenesisHash: 5f20df933584822601f9e3f8c024eb5eb252fe8cefb24d1317dc3d432e940ebb
ShelleyGenesisFile: mainnet-shelley-genesis.json
ShelleyGenesisHash: 1a3be38bcbb7911969283716ad7aa550250226b76a61fc51cc9a9a35d9276d81

##### Core protocol parameters #####

Protocol: Cardano

# The mainnet does not include the network magic into addresses. Testnets do.
RequiresNetworkMagic: RequiresNoMagic

##### Update system parameters #####

# This protocol version number gets used by block producing nodes as part
# of the system for agreeing on and synchronising protocol updates.
#
# See https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Node/Protocol/Cardano.hs#L199
LastKnownBlockVersion-Major: 3
LastKnownBlockVersion-Minor: 0
LastKnownBlockVersion-Alt: 0
MaxKnownMajorProtocolVersion: 2

# In the Byron era some software versions are also published on the chain.
# We do this only for Byron compatibility now.
ApplicationName: cardano-sl
ApplicationVersion: 1

##### Logging configuration #####

# Enable or disable logging overall
TurnOnLogging: True

##### New logging model #####
# Options for new tracing

# Use old tracing as standard for now
UseTraceDispatcher: True

TraceOptions:
  "":
    severity: Silence
    detail: DNormal
    backends:
      - Stdout MachineFormat
      - EKGBackend
      - Forwarder

  ChainDB:
     severity: Info

  ChainDB.AddBlockEvent.AddBlockValidation.ValidCandidate:
    severity: Silence

  ChainDB.InitChainSelEvent.UpdateLedgerDb:
    severity: Silence

  ConnectionManager:
    severity: Info

  AcceptPolicy:
    severity: Info

  DNSResolver:
    severity: Info

  DNSSubscription:
    severity: Info

  DiffusionInit:
    severity: Info

  ErrorPolicy:
    severity: Info

  Forge:
    severity: Info

  InboundGovernor:
    severity: Info

  IpSubscription:
    severity: Info

  LedgerPeers:
    severity: Info

  LocalErrorPolicy:
    severity: Info

  LocalRootPeers:
    severity: Info

  Mempool:
    severity: Info

  PeerSelection:
    severity: Info

  PeerSelectionActions:
    severity: Info

  PublicRootPeers:
    severity: Info


  ChainDB.AddBlockEvent.AddedBlockToQueue:
    maxFrequency: 2.0

  ChainDB.AddBlockEvent.AddedBlockToVolatileDB:
    maxFrequency: 2.0

  ChainDB.CopyToImmutableDBEvent.CopiedBlockToImmutableDB:
    maxFrequency: 2.0

  ChainDB.AddBlockEvent.AddBlockValidation.ValidCandidate:
    maxFrequency: 2.0

  BlockFetchClient.CompletedBlockFetch:
    maxFrequency: 2.0

# Options for the trace forwarder
TraceOptionForwarder:
    address:
      filePath: /tmp/forwarder.sock
    mode: Initiator

TraceOptionPeerFrequency: 2000

TraceOptionResourceFrequency: 5000

##### Stubs for legacy logging config #####

TurnOnLogMetrics: False
minSeverity: Critical
setupScribes: []
setupBackends: []
defaultScribes: []
defaultBackends: []
options: {}
