
version: 2

sphinx:
  configuration: conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: .sphinx/requirements.txt