resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/0c5b0a6619fadf22f4d62a12154e181a6d035c1c/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - cardano-api
  - cardano-cli
  - cardano-config
  - cardano-node
  - cardano-node-chairman

ghc-options:
  cardano-config:       -Wall -fwarn-redundant-constraints
  cardano-node:         -Wall -fwarn-redundant-constraints

extra-deps:
  - QuickCheck-2.12.6.1
  - Unique-0.4.7.6
  - aeson-1.4.7.1
  - assoc-1.0.1
  - base58-bytestring-0.1.0
  - base64-0.4.2
  - bech32-1.1.0
  - bifunctors-5.5.7
  - bimap-0.4.0
  - binary-0.8.7.0
  - brick-0.47
  - canonical-json-0.6.0.0
  - cborg-0.2.4.0
  - clock-0.8
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.2
  - directory-1.3.6.1
  - esqueleto-3.2.2
  - generic-monoid-0.1.0.0
  - generics-sop-0.5.1.0
  - ghc-byteorder-4.11.0.0.10
  - gray-code-0.3.1
  - hedgehog-1.0.2
  - hspec-2.7.0
  - hspec-core-2.7.0
  - hspec-discover-2.7.0
  - io-streams-1.5.1.0
  - io-streams-haproxy-1.0.1.0
  - micro-recursion-schemes-5.0.2.2
  - moo-1.2
  - network-3.1.1.1
  - persistent-2.10.5.1
  - persistent-postgresql-2.10.1.2
  - persistent-template-2.8.2.3
  - pipes-safe-2.3.2
  - primitive-0.7.1.0
  - process-1.6.8.2
  - protolude-0.3.0
  - quiet-0.2
  - quickcheck-instances-0.3.19
  - serialise-0.2.3.0
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1
  - sop-core-0.5.0.1
  - statistics-linreg-0.3
  - streaming-binary-0.3.0.1
  - systemd-2.3.0
  - tasty-hedgehog-1.0.0.2
  - text-1.2.4.0
  - text-zipper-0.10.1
  - th-abstraction-0.3.2.0
  - th-lift-0.8.1
  - th-lift-instances-0.1.14
  - these-1.1
  - time-1.8.0.4
  - time-compat-1.9.3
  - time-units-1.0.0
  - transformers-except-0.1.1
  - typerep-map-0.3.3.0
  - unix-2.7.2.2
  - webdriver-0.9.0.1
  - websockets-0.12.6.1
  - Win32-2.8.5.0
  - word-wrap-0.4.1

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 74188f62ff743c690bdf287f7fa18eaa2ee354d4
    subdirs:
      # small-steps
      - semantics/executable-spec
      - semantics/small-steps-test
      # cs-ledger
      - byron/ledger/executable-spec
      - byron/ledger/impl
      - byron/ledger/impl/test
      - byron/crypto
      - byron/crypto/test
      # cs-blockchain
      - byron/chain/executable-spec
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec
      - shelley/chain-and-ledger/shelley-spec-ledger-test

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 0c5b0a6619fadf22f4d62a12154e181a6d035c1c
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 13f44ad35d2762dbf98b3d3be56b7ba2adf515f4
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - cardano-crypto-praos
      - slotting

    # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: cde90a2b27f79187ca8310b6549331e59595e7ba

    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 8f2086aff6b315b41a39b727f860c3477205ed8a
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/backend-trace-forwarder
      - plugins/scribe-systemd
      - tracer-transformers

    # dependencies of iohk-monitoring
  - prometheus-2.1.2
  - libsystemd-journal-1.4.4
  - katip-0.8.4.0

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: f0eb6e439e7c0121476ded5e88d2f638e8aa36ac
    subdirs:
        - io-sim
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - ouroboros-consensus-byron
        - ouroboros-consensus-cardano
        - ouroboros-consensus-shelley
        - typed-protocols
        - typed-protocols-examples
        - ouroboros-network-testing
        - ouroboros-network-framework
        - Win32-network

nix:
    shell-file: nix/stack-shell.nix
