resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/4c48d34fd60991bb1b9168d293cfe31a975d858e/snapshot.yaml

packages:
  - cardano-node


extra-deps:
    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 8f5ef2af5a46e35f786b967c63d6e114a6da298b
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 4c48d34fd60991bb1b9168d293cfe31a975d858e
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 48fdef8e2cd9ca4d8745435ebff1916ce3556c70
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 81c72dab5ef6974226b5158c474cf7b3caebaea2

  - binary-0.8.7.0
  - containers-0.5.11.0
  - ekg-prometheus-adapter-0.1.0.4
  - generic-monoid-0.1.0.0
  - prometheus-2.1.1
  - pvss-0.2.0
  - time-units-1.0.0
  - libsystemd-journal-1.4.4
  - tasty-hedgehog-1.0.0.1
    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 4ad81798402ce05655b37b31b0b67f444a2f0b91
    subdirs:
      - contra-tracer
      - iohk-monitoring

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: ec96c64c665b741c17b4e38f611315bae9b0b054

  - git: https://github.com/joelwilliamson/bimap
    commit: 013a0639c222b3f5572ae20ce364815e5d8f2156

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: eb5900dacd357a7938b9eed1db8d19fbc11ff702
    subdirs:
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols
        - typed-protocols-cbor

  - brick-0.47@sha256:4936c50acfdf09620dad5217fb384fc0d59626f75abed8b48250b419ec2ab623
  - config-ini-0.2.4.0@sha256:38a6d484d471c6fac81445de2eac8c4e8c82760962fca5491ae1c3bfca9c4047
  - data-clist-0.1.2.2@sha256:4d70add0a200a178853cd37c6469101bac3c36aebb3aa9c503ff225211b1a8c9
  - text-zipper-0.10.1@sha256:8b73a97a3717a17df9b0a722b178950c476ff2268ca5c583e99d010c94af849e
  - word-wrap-0.4.1@sha256:f72233b383ef569c557bfd9812cbb8e306c415ce509082c0bd15ee51c0239ccc

flags:
  iohk-monitoring:
    disable-prometheus: true

nix:
  shell-file: nix/stack-shell.nix
