resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/3c40edcf5bdba8721d3430d0aaaeea8770ce9bec/snapshot.yaml

packages:
  - cardano-config
  - cardano-node

ghc-options:
  cardano-config:   -Wall -Werror -fwarn-redundant-constraints
  cardano-node:     -Wall -Werror -fwarn-redundant-constraints

extra-deps:
  - binary-0.8.7.0
  - bimap-0.4.0
  - containers-0.5.11.0
  - generic-monoid-0.1.0.0
  - gray-code-0.3.1
  - moo-1.2
  - time-units-1.0.0
  - tasty-hedgehog-1.0.0.1
  - transformers-except-0.1.1
  - brick-0.47
  - config-ini-0.2.4.0
  - data-clist-0.1.2.2
  - text-zipper-0.10.1
  - Unique-0.4.7.6
  - word-wrap-0.4.1

    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 52ffa26e6d5a204345ddc3e375b17cf1c96d3412
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: c1f9d85f50a6e71b2376618cb57656a1b7192ef1
    subdirs:
      # small-steps
      - byron/semantics/executable-spec
      # cs-ledger
      - byron/ledger/executable-spec
      # cs-blockchain
      - byron/chain/executable-spec

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3c40edcf5bdba8721d3430d0aaaeea8770ce9bec
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 057d8a9a3e751f88fc7677df5713c5ecc47a37c4
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: f700afeb24163332dc00306508ca410b7873521d
    subdirs:
      - cardano-shell

    # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 4956b32f039579a0e7e4fd10793f65b4c77d9044
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-editor
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/scribe-systemd

    # dependencies of iohk-monitoring
  - prometheus-2.1.2
  - libsystemd-journal-1.4.4
  - katip-0.8.3.0
  - git: https://github.com/CodiePP/ekg-prometheus-adapter
    commit: 1a258b6df7d9807d4c4ff3e99722223d31a2c320

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: babf1a855e6bc745321b2516837f5cac174b6943
    subdirs:
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols
        - typed-protocols-cbor

nix:
  shell-file: nix/stack-shell.nix
