resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/68648612f916e8adaf6c9ca5fe39bc6712470a6a/snapshot.yaml

packages:
  - .

extra-deps:
    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: b81e722c28ed7d65d93c70b43ea744afd95ea1c3
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: a21f83d9407b2955fbaea4ce8a79b262361112aa
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 501d91e426ae84ce0ae056be38bd3db594af9fc2
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 71fb36665338491e92d3ef14c20ae38ad6882c94

  - containers-0.5.11.0
  - ekg-prometheus-adapter-0.1.0.4
  - prometheus-2.1.1
  - pvss-0.2.0
  - time-units-1.0.0
  - libsystemd-journal-1.4.4
  - tasty-hedgehog-1.0.0.1
    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: b2022cf7f5925e486f9e0a31f6f6d02145d5ebda
    subdirs:
      - contra-tracer
      - iohk-monitoring

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4

  - git: https://github.com/joelwilliamson/bimap
    commit: 013a0639c222b3f5572ae20ce364815e5d8f2156

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: f3f5f4903d88bcbd52496c38046732b22515cec2
    subdirs:
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols
        - typed-protocols-cbor

  - brick-0.47@sha256:4936c50acfdf09620dad5217fb384fc0d59626f75abed8b48250b419ec2ab623
  - config-ini-0.2.4.0@sha256:38a6d484d471c6fac81445de2eac8c4e8c82760962fca5491ae1c3bfca9c4047
  - data-clist-0.1.2.2@sha256:4d70add0a200a178853cd37c6469101bac3c36aebb3aa9c503ff225211b1a8c9
  - text-zipper-0.10.1@sha256:8b73a97a3717a17df9b0a722b178950c476ff2268ca5c583e99d010c94af849e
  - word-wrap-0.4.1@sha256:f72233b383ef569c557bfd9812cbb8e306c415ce509082c0bd15ee51c0239ccc

flags:
  iohk-monitoring:
    disable-prometheus: true

nix:
  shell-file: nix/stack-shell.nix
