resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/ad19158c7599bc5d50fe7cb0111a1488a139a381/snapshot.yaml

packages:
  - cardano-config
  - cardano-node

ghc-options:
  cardano-config:   -Wall -Werror -fwarn-redundant-constraints
  cardano-node:     -Wall -Werror -fwarn-redundant-constraints

extra-deps:
  - binary-0.8.7.0
  - bimap-0.4.0
  - containers-0.5.11.0
  - generic-monoid-0.1.0.0
  - gray-code-0.3.1
  - moo-1.2
  - time-units-1.0.0
  - tasty-hedgehog-1.0.0.1
  - transformers-except-0.1.1
  - brick-0.47
  - config-ini-0.2.4.0
  - data-clist-0.1.2.2
  - text-zipper-0.10.1
  - Unique-0.4.7.6
  - word-wrap-0.4.1

    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 181f69af290412abecefc07e1b26e77a453755ff
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: ffb39c870d4873b8501b9df05101d9c9b3e84a39
    subdirs:
      # small-steps
      - byron/semantics/executable-spec
      # cs-ledger
      - byron/ledger/executable-spec
      # cs-blockchain
      - byron/chain/executable-spec

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: ad19158c7599bc5d50fe7cb0111a1488a139a381
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 5c575d46afbfe333de0ccba70b084db8302abf42
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 8abae427c44f0b447117f78e2c1f5006dac2edf8
    subdirs:
      - cardano-shell

    # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: b4268cedecbbe2a35437effc17a8af10abda8ea8
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-editor
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/scribe-systemd

    # dependencies of iohk-monitoring
  - prometheus-2.1.2
  - libsystemd-journal-1.4.4
  - katip-0.8.3.0
  - git: https://github.com/CodiePP/ekg-prometheus-adapter
    commit: 1a258b6df7d9807d4c4ff3e99722223d31a2c320

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 97500309e161627141605f82b01cddc5f6feea11
    subdirs:
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols
        - typed-protocols-cbor

nix:
  shell-file: nix/stack-shell.nix
