resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/56fadcea03417771f4b3666fd1dfc9bad8df1484/snapshot.yaml

packages:
  - cardano-config
  - cardano-node

ghc-options:
  cardano-config:   -Wall -Werror -fwarn-redundant-constraints
  cardano-node:     -Wall -Werror -fwarn-redundant-constraints

extra-deps:

  - git: https://github.com/input-output-hk/cardano-base
    commit: 0e26a4f00324100b4c34f2a9c7606ae03e94d7a2
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class












  # - git: https://github.com/input-output-hk/cardano-crypto
  #   commit: 4590efa638397e952a51a8994b5543e4ea3c1ecd



  - git: https://github.com/input-output-hk/cardano-ledger
    commit: db1c822f1847e40eb340152b95ab3138a10f92df
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

















  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 56fadcea03417771f4b3666fd1dfc9bad8df1484
    subdirs:
      - .
      - test






  - git: https://github.com/input-output-hk/cardano-shell
    commit: 18906dd8c109380c4b1fa20ed35100e48135aac3


    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49



    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: e22be186e0b1018260ed7c5166871f82a869b94d
    subdirs:
      - contra-tracer
      - iohk-monitoring






  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 2ad7dced59caece77b6a5e06914aa37d8a3bba23
    subdirs:
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols
        - typed-protocols-cbor



























  - git: https://github.com/joelwilliamson/bimap
    commit: 013a0639c222b3f5572ae20ce364815e5d8f2156



  - git: http://github.com/well-typed/canonical-json
    commit: ddfe3593b80b5ceb88842bb7a6f2268df75d2c2f

  - binary-0.8.7.0
  - containers-0.5.11.0
  - ekg-prometheus-adapter-0.1.0.4
  - generic-monoid-0.1.0.0
  - prometheus-2.1.1
  - pvss-0.2.0
  - time-units-1.0.0
  - libsystemd-journal-1.4.4
  - tasty-hedgehog-1.0.0.1
  - transformers-except-0.1.1

    #Ouroboros-network dependencies

  - brick-0.47@sha256:4936c50acfdf09620dad5217fb384fc0d59626f75abed8b48250b419ec2ab623
  - config-ini-0.2.4.0@sha256:38a6d484d471c6fac81445de2eac8c4e8c82760962fca5491ae1c3bfca9c4047
  - data-clist-0.1.2.2@sha256:4d70add0a200a178853cd37c6469101bac3c36aebb3aa9c503ff225211b1a8c9
  - text-zipper-0.10.1@sha256:8b73a97a3717a17df9b0a722b178950c476ff2268ca5c583e99d010c94af849e
  - word-wrap-0.4.1@sha256:f72233b383ef569c557bfd9812cbb8e306c415ce509082c0bd15ee51c0239ccc

flags:
  iohk-monitoring:
    disable-prometheus: true

nix:
  shell-file: nix/stack-shell.nix
