resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/71ea865408f2e03e6d6832359423546699730849/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - cardano-api
  - cardano-cli
  - cardano-config
  - cardano-node
  - cardano-node-chairman

ghc-options:
  cardano-config:       -Wall -fwarn-redundant-constraints
  cardano-node:         -Wall -fwarn-redundant-constraints

allow-newer: true

extra-deps:
  - QuickCheck-2.12.6.1
  - quickcheck-instances-0.3.19
  - base58-bytestring-0.1.0
  - base64-0.4.2
  - bech32-1.0.2
  - brick-0.47
  - binary-0.8.7.0
  - bimap-0.4.0
  - canonical-json-0.6.0.0
  - cborg-0.2.4.0
  - clock-0.8
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.2
  - generic-monoid-0.1.0.0
  - ghc-byteorder-4.11.0.0.10
  - gray-code-0.3.1
  - hedgehog-1.0.2
  - hedgehog-corpus-0.2.0
  - hedgehog-quickcheck-0.1.1
  - hspec-2.7.0
  - hspec-core-2.7.0
  - hspec-discover-2.7.0
  - io-streams-1.5.1.0
  - io-streams-haproxy-1.0.1.0
  - micro-recursion-schemes-5.0.2.2
  - moo-1.2
  - network-3.1.1.1
  - quiet-0.2
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1
  - statistics-linreg-0.3
  - streaming-binary-0.3.0.1
  - systemd-2.3.0
  - tasty-hedgehog-1.0.0.2
  - text-1.2.4.0
  - text-ansi-0.1.0
  - text-zipper-0.10.1
  - th-lift-instances-0.1.14
  - time-units-1.0.0
  - transformers-except-0.1.1
  - Unique-0.4.7.6
  - word-wrap-0.4.1
  - websockets-0.12.6.1

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 9591f2d4b1915bcacd4797de563ca8a17d3b06f9
    subdirs:
      # small-steps
      - semantics/executable-spec
      # cs-ledger
      - byron/ledger/executable-spec
      - byron/ledger/impl
      - byron/crypto
      - byron/ledger/impl/test
      - byron/crypto/test
      # cs-blockchain
      - byron/chain/executable-spec
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec
      - shelley/chain-and-ledger/shelley-spec-ledger-test

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 71ea865408f2e03e6d6832359423546699730849
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: df8687488449f71dce3d881800c21e41fe1b7fc1
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting


    # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 312198a1523736181ef7ddab15958bb32a9d9052

    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 8190b00d6930927a812baff97d02566176b6bd3b
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/backend-trace-forwarder
      - plugins/scribe-systemd
      - tracer-transformers

    # dependencies of iohk-monitoring
  - prometheus-2.1.2
  - libsystemd-journal-1.4.4
  - katip-0.8.4.0

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: aecfe77de784e6c75108172802ee59d2d7087eaf
    subdirs:
        - io-sim
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - ouroboros-consensus-byron
        - ouroboros-consensus-cardano
        - ouroboros-consensus-shelley
        - typed-protocols
        - typed-protocols-examples
        - ouroboros-network-testing
        - ouroboros-network-framework
        - Win32-network

nix:
    shell-file: nix/stack-shell.nix
