resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/a136c4242b9c9f6124b811329bc8ccdfd86c514e/snapshot.yaml

packages:
  - .
  - validate-mainnet

extra-deps:
    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 761feffb241c2db934c599dc330131ddee034322
    subdirs:
      - .
      - crypto
      - crypto/test
      - test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: a136c4242b9c9f6124b811329bc8ccdfd86c514e
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: b676160954cea07d4378ccca870a61242bc188a2
    subdirs:
      - binary
      - binary/test

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: b9f9ca51f8cb90387e48711646ab4f8e6c21916b

    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: b2857c646e0643ec6016faa246391fd7d69bdd9e
    subdirs:
      - contra-tracer
      - iohk-monitoring
  - time-units-1.0.0

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4

  - git: https://github.com/joelwilliamson/bimap
    commit: 997fbb38b08dec14d225d064dac05b0a85f4ceae

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: b3a46e40ba95204866890caf9713c5c2af282141
    subdirs:
        - io-sim-classes
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols

flags:
  iohk-monitoring:
    disable-prometheus: true

