resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/a136c4242b9c9f6124b811329bc8ccdfd86c514e/snapshot.yaml

packages:
  - .

extra-deps:
    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: fbffd18089041efb1f8d1896c5410bc2302811ef
    subdirs:
      - .
      - crypto
      - crypto/test
      - test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: a136c4242b9c9f6124b811329bc8ccdfd86c514e
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: b676160954cea07d4378ccca870a61242bc188a2
    subdirs:
      - binary
      - binary/test

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: f6fcda280ddd1d4ef87e5203d65d132f924a6e39

  - containers-0.5.11.0
  - ekg-prometheus-adapter-0.1.0.4
  - prometheus-2.1.1
  - time-units-1.0.0
  - libsystemd-journal-1.4.4
    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 9129241a1306e2418bb775c63ad8a3ccd785c068
    subdirs:
      - contra-tracer
      - iohk-monitoring

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4

  - git: https://github.com/joelwilliamson/bimap
    commit: 997fbb38b08dec14d225d064dac05b0a85f4ceae

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 1c291da70decc003b474b192e335e86e80c252b3
    subdirs:
        - io-sim-classes
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols

flags:
  iohk-monitoring:
    disable-prometheus: true

nix:
  shell-file: nix/stack-shell.nix
