resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/fa7a16291d3e93b068d9b13620fc81c88b5600f0/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - cardano-config
  - cardano-node

ghc-options:
  cardano-config:   -Wall -Werror -fwarn-redundant-constraints
  cardano-node:     -Wall -Werror -fwarn-redundant-constraints

allow-newer: true

extra-deps:
  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 4590efa638397e952a51a8994b5543e4ea3c1ecd

  - QuickCheck-2.12.6.1
  - quickcheck-instances-0.3.19
  - hspec-2.7.0
  - hspec-core-2.7.0
  - hspec-discover-2.7.0
  - text-1.2.4.0
  - base58-bytestring-0.1.0
  # Waiting on Stackage release
  - hedgehog-1.0.2
  - micro-recursion-schemes-5.0.2.2
  - streaming-binary-0.3.0.1
  - cborg-0.2.2.1
  - canonical-json-0.6.0.0
  - brick-0.47
  - binary-0.8.7.0
  - bimap-0.4.0
  - clock-0.8
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.2
  - generic-monoid-0.1.0.0
  - gray-code-0.3.1
  - io-streams-1.5.1.0
  - io-streams-haproxy-1.0.1.0
  - moo-1.2
  - network-3.1.1.1
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1
  - statistics-linreg-0.3
  - time-units-1.0.0
  - tasty-hedgehog-1.0.0.2
  - transformers-except-0.1.1
  - text-zipper-0.10.1
  - Unique-0.4.7.6
  - word-wrap-0.4.1
  - websockets-0.12.6.1
  - th-lift-instances-0.1.14

    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 86f0cb4705f46307e4c89e7ef4c90142882cce54
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 318f5a1594a23aedadb3977ddd5a32230c8be4fe
    subdirs:
      # small-steps
      - byron/semantics/executable-spec
      # cs-ledger
      - byron/ledger/executable-spec
      # cs-blockchain
      - byron/chain/executable-spec

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: fa7a16291d3e93b068d9b13620fc81c88b5600f0
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 3c2791584d3f43aa18e9cc13c490239b4c3dcbd2
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: bc3563c952d9f3635e1c76749b86b0a24f7e4b83
    subdirs:
      - cardano-shell

    # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 49b347d892d82dce23eb692722649cd8a1149406
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-editor
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/scribe-systemd
      - tracer-transformers

    # dependencies of iohk-monitoring
  - prometheus-2.1.2
  - libsystemd-journal-1.4.4
  - katip-0.8.3.0

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: f5741efd37c5558d8a29d0d2b142e01f650a3d45
    subdirs:
        - io-sim
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols
        - typed-protocols-examples
        - ouroboros-network-framework

nix:
  shell-file: nix/stack-shell.nix
