resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - cardano-config
  - cardano-node

ghc-options:
  cardano-config:       -Wall -Werror -fwarn-redundant-constraints
  cardano-node:         -Wall -Werror -fwarn-redundant-constraints

allow-newer: true

extra-deps:
  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - QuickCheck-2.12.6.1
  - quickcheck-instances-0.3.19
  - hspec-2.7.0
  - hspec-core-2.7.0
  - hspec-discover-2.7.0
  - text-1.2.4.0
  - base58-bytestring-0.1.0
  # Waiting on Stackage release
  - hedgehog-1.0.2
  - micro-recursion-schemes-5.0.2.2
  - streaming-binary-0.3.0.1
  - canonical-json-0.6.0.0
  - brick-0.47
  - binary-0.8.7.0
  - bimap-0.4.0
  - clock-0.8
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.2
  - generic-monoid-0.1.0.0
  - gray-code-0.3.1
  - io-streams-1.5.1.0
  - io-streams-haproxy-1.0.1.0
  - moo-1.2
  - network-3.1.1.1
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1
  - statistics-linreg-0.3
  - time-units-1.0.0
  - tasty-hedgehog-1.0.0.2
  - transformers-except-0.1.1
  - text-zipper-0.10.1
  - Unique-0.4.7.6
  - word-wrap-0.4.1
  - websockets-0.12.6.1
  - th-lift-instances-0.1.14

    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 357ed656ad81fcddb401ceb656d6c2a6a177a0fa
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 5c5854be017f75c703b11c1aad4b765f511ee70e
    subdirs:
      # small-steps
      - semantics/executable-spec
      # cs-ledger
      - byron/ledger/executable-spec
      # cs-blockchain
      - byron/chain/executable-spec
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec
      - shelley/chain-and-ledger/executable-spec/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 42c57fed487b61c13a68a1600a6675ad987822d0
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 8387be2c5d4f7060a48bceae119973c6382df57c
    subdirs:
      - cardano-shell

    # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 285912da4bea7719e85557bb5b42ad8c78c16b0a
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/backend-trace-forwarder
      - plugins/scribe-systemd
      - tracer-transformers

    # dependencies of iohk-monitoring
  - prometheus-2.1.2
  - libsystemd-journal-1.4.4
  - katip-0.8.3.0

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: dbc48d30c5e3a46d28b7c25a15141d3518982c70
    subdirs:
        - io-sim
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - ouroboros-consensus-byron
        - ouroboros-consensus/ouroboros-consensus-mock
        - ouroboros-consensus-cardano
        - ouroboros-consensus-shelley
        - typed-protocols
        - typed-protocols-examples
        - ouroboros-network-testing
        - ouroboros-network-framework
        - Win32-network

    # Includes updated pretty printing function
  - git: https://github.com/well-typed/cborg.git
    commit: 42a83192749774268337258f4f94c97584b80ca6
    subdirs:
        - cborg

    # Includes a windows build fix (https://github.com/snoyberg/http-client/pull/430)
  - git: https://github.com/snoyberg/http-client.git
    commit: 1a75bdfca014723dd5d40760fad854b3f0f37156
    subdirs:
        - http-client

nix:
    shell-file: nix/stack-shell.nix
