resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/a21f83d9407b2955fbaea4ce8a79b262361112aa/snapshot.yaml

packages:
  - .

extra-deps:
    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 7f5263eac329d73a0626fc0d9603dec2cd51d352
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: a21f83d9407b2955fbaea4ce8a79b262361112aa
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: b676160954cea07d4378ccca870a61242bc188a2
    subdirs:
      - binary
      - binary/test

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 64cdb7f84ab34934d5001031c911ca3615d2d2a4

  - binary-0.8.7.0
  - containers-0.5.11.0
  - ekg-prometheus-adapter-0.1.0.4
  - prometheus-2.1.1
  - time-units-1.0.0
  - libsystemd-journal-1.4.4
  - tasty-hedgehog-1.0.0.1
    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 9129241a1306e2418bb775c63ad8a3ccd785c068
    subdirs:
      - contra-tracer
      - iohk-monitoring

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4

  - git: https://github.com/joelwilliamson/bimap
    commit: 997fbb38b08dec14d225d064dac05b0a85f4ceae

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 8f999f3a0e7765a673654486c79951a32e4a5c37
    subdirs:
        - io-sim-classes
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols

flags:
  iohk-monitoring:
    disable-prometheus: true

nix:
  shell-file: nix/stack-shell.nix
