#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

# shellcheck disable=SC2154
echo "${colourRed}Not yet implemented${colourReset}"

# ${CARDANO_CLI} shelley stake-pool registration-certificate
# assert_file_exists "${TEST_DIR}/key-gen-staking.vkey"
# assert_file_exists "${TEST_DIR}/key-gen-staking.skey"

# assert_string 'StakeVerificationKeyShelley_ed25519' "${TEST_DIR}/key-gen-staking.vkey"
# assert_string 'StakeSigningKeyShelley_ed25519' "${TEST_DIR}/key-gen-staking.skey"

report_result ${error}
