#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

setup_data_dir "${testname}"

error=0

${CARDANO_CLI} shelley genesis initial-txin \
    --verification-key-file "${DATA_DIR}/genesis-utxo.vkey" \
    > "${TEST_DIR}/utxo-hash.hex"
fail_on_error $?

assert_line_count 1 "${TEST_DIR}/utxo-hash.hex"

report_result ${error}
