#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

setup_data_dir "${testname}"

error=0

${CARDANO_CLI} shelley transaction calculate-min-fee \
    --tx-in-count 32 \
    --tx-out-count 27 \
    --byron-witness-count 5 \
    --witness-count 10 \
    --testnet-magic 4036000900 \
    --protocol-params-file "${DATA_DIR}/protocol-params.json" \
    --tx-body-file "${DATA_DIR}/tx-body-file" \
    > "${TEST_DIR}/min-fee.txt"
fail_on_error $?

assert_file_exists "${TEST_DIR}/min-fee.txt"

line_count=$(wc -l < "${TEST_DIR}/min-fee.txt")
if test "${line_count}" -ne 1 ; then
  echo "Error: Expected only a single line of output."
  cat "${TEST_DIR}/min-fee.txt"
  error=1
  fi

assert_string '2594002' "${TEST_DIR}/min-fee.txt"

report_result ${error}
