-- | Shared path conventions for cardano-testnet output directories.
--
-- Both @cardano-testnet@ (producer) and consumers of generated
-- testnet configurations depend on this module so that directory
-- layout changes are kept in sync at compile time.
module Cardano.Node.Testnet.Paths
  ( -- * Node paths
    defaultNodeName
  , defaultNodeDataDir
  , defaultConfigFile
  , defaultPortFile
  , defaultNodeEnvFile
    -- * Socket paths
  , defaultSocketDir
  , defaultSocketName
  , defaultSocketPath
    -- * UTxO key paths
  , defaultUtxoKeyDir
  , defaultUtxoSKeyPath
  , defaultUtxoVKeyPath
  , defaultUtxoAddrPath
    -- * Genesis paths
  , defaultGenesisFilepath
    -- * Committee key paths
  , defaultCommitteeName
  , defaultCommitteeKeysDir
  , defaultCommitteeVkeyFp
  , defaultCommitteeSkeyFp
    -- * DRep key paths
  , defaultDRepName
  , defaultDRepKeysDir
  , defaultDRepDir
  , defaultDRepVkeyFp
  , defaultDRepSkeyFp
    -- * SPO key paths
  , defaultSpoName
  , defaultSpoKeysDir
  , defaultSpoColdVKeyFp
  , defaultSpoColdSKeyFp
  , defaultSpoVrfVKeyFp
  , defaultSpoVrfSKeyFp
  , defaultSpoStakingRewardVKeyFp
  , defaultSpoStakingRewardSKeyFp
  , defaultSpoKesVKeyFp
  , defaultSpoKesSKeyFp
  , defaultSpoOpcertCounterFp
  , defaultSpoOpcertCertFp
  , defaultSpoByronDelegationCertFp
  , defaultSpoByronDelegateKeyFp
    -- * Delegator key paths
  , defaultDelegatorName
  , defaultDelegatorStakeKeysDir
  , defaultDelegatorStakeDir
  , defaultDelegatorStakeVKeyFp
  , defaultDelegatorStakeSKeyFp
  ) where

import           Cardano.Api (CardanoEra, docToString, pretty)

import           Data.Char (toLower)
import           System.FilePath ((</>))

-- ---------------------------------------------------------------------
-- Node paths
-- ---------------------------------------------------------------------

-- | The name of a node: @"node" <> show n@
defaultNodeName :: Int -> String
defaultNodeName n = "node" <> show n

-- | Relative path to a node's data directory: @"node-data" </> defaultNodeName n@
defaultNodeDataDir :: Int -> FilePath
defaultNodeDataDir n = "node-data" </> defaultNodeName n

-- | Main node configuration file name: @"configuration.yaml"@
defaultConfigFile :: FilePath
defaultConfigFile = "configuration.yaml"

-- | Relative path to a node's port file: @defaultNodeDataDir n </> "port"@
defaultPortFile :: Int -> FilePath
defaultPortFile n = defaultNodeDataDir n </> "port"

-- | Relative path to a node's env file: @defaultNodeDataDir n </> "env"@
defaultNodeEnvFile :: Int -> FilePath
defaultNodeEnvFile n = defaultNodeDataDir n </> "env"

-- ---------------------------------------------------------------------
-- Socket paths
-- ---------------------------------------------------------------------

-- | Socket directory name: @"socket"@
defaultSocketDir :: FilePath
defaultSocketDir = "socket"

-- | Socket file name: @"sock"@
defaultSocketName :: FilePath
defaultSocketName = "sock"

-- | Relative path to a node's socket: @defaultSocketDir </> defaultNodeName n </> defaultSocketName@
defaultSocketPath :: Int -> FilePath
defaultSocketPath n = defaultSocketDir </> defaultNodeName n </> defaultSocketName

-- ---------------------------------------------------------------------
-- UTxO key paths
-- ---------------------------------------------------------------------

-- | Relative path to a UTxO key directory: @"utxo-keys" </> "utxo" <> show n@
defaultUtxoKeyDir :: Int -> FilePath
defaultUtxoKeyDir n = "utxo-keys" </> "utxo" <> show n

-- | Relative path to a UTxO signing key: @defaultUtxoKeyDir n </> "utxo.skey"@
defaultUtxoSKeyPath :: Int -> FilePath
defaultUtxoSKeyPath n = defaultUtxoKeyDir n </> "utxo.skey"

-- | Relative path to a UTxO verification key: @defaultUtxoKeyDir n </> "utxo.vkey"@
defaultUtxoVKeyPath :: Int -> FilePath
defaultUtxoVKeyPath n = defaultUtxoKeyDir n </> "utxo.vkey"

-- | Relative path to a UTxO address file: @defaultUtxoKeyDir n </> "utxo.addr"@
defaultUtxoAddrPath :: Int -> FilePath
defaultUtxoAddrPath n = defaultUtxoKeyDir n </> "utxo.addr"

-- ---------------------------------------------------------------------
-- Genesis paths
-- ---------------------------------------------------------------------

-- This path is actually generated by create-testnet-data. Don't change it.
defaultGenesisFilepath :: CardanoEra a -> FilePath
defaultGenesisFilepath era =
  map toLower (docToString (pretty era)) <> "-genesis.json"

-- ---------------------------------------------------------------------
-- Committee key paths
-- ---------------------------------------------------------------------

defaultCommitteeName :: Int -> String
defaultCommitteeName n = "committee" <> show n

defaultCommitteeKeysDir :: FilePath
defaultCommitteeKeysDir = "committee-keys"

defaultCommitteeVkeyFp :: Int -> FilePath
defaultCommitteeVkeyFp n = defaultCommitteeKeysDir </> defaultCommitteeName n <> ".vkey"

defaultCommitteeSkeyFp :: Int -> FilePath
defaultCommitteeSkeyFp n = defaultCommitteeKeysDir </> defaultCommitteeName n <> ".skey"

-- ---------------------------------------------------------------------
-- DRep key paths
-- ---------------------------------------------------------------------

defaultDRepName :: Int -> String
defaultDRepName n = "drep" <> show n

defaultDRepKeysDir :: FilePath
defaultDRepKeysDir = "drep-keys"

defaultDRepDir :: Int -> FilePath
defaultDRepDir n = defaultDRepKeysDir </> defaultDRepName n

defaultDRepVkeyFp :: Int -> FilePath
defaultDRepVkeyFp n = defaultDRepDir n </> "drep.vkey"

defaultDRepSkeyFp :: Int -> FilePath
defaultDRepSkeyFp n = defaultDRepDir n </> "drep.skey"

-- ---------------------------------------------------------------------
-- SPO key paths
-- ---------------------------------------------------------------------

-- | The name of a SPO, used in file system operations
defaultSpoName :: Int -> String
defaultSpoName n = "pool" <> show n

-- | The relative path where the SPO keys for the node are stored
defaultSpoKeysDir :: Int -> FilePath
defaultSpoKeysDir n = "pools-keys" </> defaultSpoName n

-- | The relative path to SPO cold verification key in directories created by cardano-testnet
defaultSpoColdVKeyFp :: Int -> FilePath
defaultSpoColdVKeyFp n = defaultSpoKeysDir n </> "cold.vkey"

-- | The relative path to SPO cold secret key in directories created by cardano-testnet
defaultSpoColdSKeyFp :: Int -> FilePath
defaultSpoColdSKeyFp n = defaultSpoKeysDir n </> "cold.skey"

defaultSpoVrfVKeyFp :: Int -> FilePath
defaultSpoVrfVKeyFp n = defaultSpoKeysDir n </> "vrf.vkey"

defaultSpoVrfSKeyFp :: Int -> FilePath
defaultSpoVrfSKeyFp n = defaultSpoKeysDir n </> "vrf.skey"

defaultSpoStakingRewardVKeyFp :: Int -> FilePath
defaultSpoStakingRewardVKeyFp n = defaultSpoKeysDir n </> "staking-reward.vkey"

defaultSpoStakingRewardSKeyFp :: Int -> FilePath
defaultSpoStakingRewardSKeyFp n = defaultSpoKeysDir n </> "staking-reward.skey"

defaultSpoKesVKeyFp :: Int -> FilePath
defaultSpoKesVKeyFp n = defaultSpoKeysDir n </> "kes.vkey"

defaultSpoKesSKeyFp :: Int -> FilePath
defaultSpoKesSKeyFp n = defaultSpoKeysDir n </> "kes.skey"

defaultSpoOpcertCounterFp :: Int -> FilePath
defaultSpoOpcertCounterFp n = defaultSpoKeysDir n </> "opcert.counter"

defaultSpoOpcertCertFp :: Int -> FilePath
defaultSpoOpcertCertFp n = defaultSpoKeysDir n </> "opcert.cert"

defaultSpoByronDelegationCertFp :: Int -> FilePath
defaultSpoByronDelegationCertFp n = defaultSpoKeysDir n </> "byron-delegation.cert"

defaultSpoByronDelegateKeyFp :: Int -> FilePath
defaultSpoByronDelegateKeyFp n = defaultSpoKeysDir n </> "byron-delegate.key"

-- ---------------------------------------------------------------------
-- Delegator key paths
-- ---------------------------------------------------------------------

defaultDelegatorName :: Int -> String
defaultDelegatorName n = "delegator" <> show n

defaultDelegatorStakeKeysDir :: FilePath
defaultDelegatorStakeKeysDir = "stake-delegators"

defaultDelegatorStakeDir :: Int -> FilePath
defaultDelegatorStakeDir n = defaultDelegatorStakeKeysDir </> defaultDelegatorName n

defaultDelegatorStakeVKeyFp :: Int -> FilePath
defaultDelegatorStakeVKeyFp n = defaultDelegatorStakeDir n </> "staking.vkey"

defaultDelegatorStakeSKeyFp :: Int -> FilePath
defaultDelegatorStakeSKeyFp n = defaultDelegatorStakeDir n </> "staking.skey"
