#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

setup_data_dir "${testname}"

error=0

${CARDANO_CLI} shelley address key-hash \
    --verification-key-file "${DATA_DIR}/address.vkey" \
    > "${TEST_DIR}/vkey-hash"

assert_file_exists "${TEST_DIR}/vkey-hash"

assert_line_count 1 "${TEST_DIR}/vkey-hash"

report_result ${error}
