#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

# Run the version command and pipe output to /dev/null.
${CARDANO_CLI} version > /dev/null
error=$?

report_result ${error}
