#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

setup_data_dir "${testname}"

error=0

${CARDANO_CLI} shelley stake-address build \
    --staking-verification-key-file "${DATA_DIR}/staking.vkey" \
    > "${TEST_DIR}/reward-address.hex"
fail_on_error $?

assert_file_exists "${TEST_DIR}/reward-address.hex"
assert_line_count 1 "${TEST_DIR}/reward-address.hex"

report_result ${error}
