#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

${CARDANO_CLI} shelley genesis key-gen-utxo \
    --verification-key-file "${TEST_DIR}/utxo.vkey" \
    --signing-key-file "${TEST_DIR}/utxo.skey"

assert_file_exists "${TEST_DIR}/utxo.vkey"
assert_file_exists "${TEST_DIR}/utxo.skey"

assert_string 'GenesisUTxOVerificationKey_ed25519' "${TEST_DIR}/utxo.vkey"
assert_string 'GenesisUTxOSigningKey_ed25519' "${TEST_DIR}/utxo.skey"

report_result ${error}
