#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

${CARDANO_CLI} shelley node key-gen-stake-pool \
    --verification-key-file "${TEST_DIR}/key-gen-stake-pool.vkey" \
    --signing-key-file "${TEST_DIR}/key-gen-stake-pool.skey"

assert_file_exists "${TEST_DIR}/key-gen-stake-pool.vkey"
assert_file_exists "${TEST_DIR}/key-gen-stake-pool.skey"

assert_string 'VerificationKeyStakePoolShelley' "${TEST_DIR}/key-gen-stake-pool.vkey"
assert_string 'SigningKeyShelley' "${TEST_DIR}/key-gen-stake-pool.skey"

report_result ${error}
