#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

# Does it make sense to add this test ? After checking it looks like a clone of:
# https://github.com/input-output-hk/cardano-node/blob/master/cardano-cli/test/cli/node-key-gen/run
# the only difference is the title. which I added to checks at the bottom - is it worth to add this then ?

${CARDANO_CLI} shelley genesis key-gen-delegate \
    --verification-key-file "${TEST_DIR}/key-gen.vkey" \
    --signing-key-file "${TEST_DIR}/key-gen.skey" \
    --operational-certificate-issue-counter "${TEST_DIR}/op-cert.counter"

assert_file_exists "${TEST_DIR}/key-gen.vkey"
assert_file_exists "${TEST_DIR}/key-gen.skey"
assert_file_exists "${TEST_DIR}/op-cert.counter"

# Check type:
assert_string 'GenesisDelegateVerificationKey_ed25519' "${TEST_DIR}/key-gen.vkey"
assert_string 'GenesisDelegateSigningKey_ed25519' "${TEST_DIR}/key-gen.skey"
assert_string 'NodeOperationalCertificateIssueCounter' "${TEST_DIR}/op-cert.counter"

# Check title:
assert_string 'Genesis delegate operator key' "${TEST_DIR}/key-gen.vkey"
assert_string 'Genesis delegate operator key' "${TEST_DIR}/key-gen.skey"

report_result ${error}
