usage_chain_fragment() {
    usage "chain-fragment" "Export profile runs as ouroboros-consensus-tools chain fragments" <<EOF
    $(helpcmd export CONSENSUS-TOOLS-DIR [RUN])
                                 Export RUN (default: $(green current)) as a chain
                                 fragment usable by the $(blue beacon) tool: copies the
                                 node's $(blue db/), the byron/alonzo/conway/dijkstra
                                 genesis files and the untrimmed shelley genesis,
                                 patches $(blue config.json)'s genesis paths, and adds
                                 a minimal $(blue beacon-data/chain/chain-register.json)
                                 entry (with $(blue chFromSlot) left unset, for manual
                                 refinement once a representative starting slot has
                                 been picked).

  $(red chain-fragment) $(blue options):
    $(helpopt --force)          Overwrite an existing destination directory
EOF
}

chain_fragment() {
local force=
while test $# -gt 0
do case "$1" in
       --force ) force=t;;
       * ) break;; esac; shift; done

local op=${1:?$(usage_chain_fragment)}; shift

case "$op" in

export )
    local usage="USAGE: wb chain-fragment [--force] $op CONSENSUS-TOOLS-DIR [RUN]"
    local consensus_tools_dir=${1:?$usage}; shift
    local run_tag=${1:-$(run current-tag)}

    command -v jq >/dev/null 2>&1 || fatal "chain-fragment: jq is required"

    local run_dir=$(run compute-path "$run_tag")
    local node_dir="$run_dir"/node-0
    local genesis_dir="$run_dir"/genesis

    test -d "$run_dir"                               || fatal "chain-fragment: run directory not found: $run_dir"
    test -d "$consensus_tools_dir"                    || fatal "chain-fragment: ouroboros-consensus-tools path not found: $consensus_tools_dir"
    test -d "$node_dir/db"                             || fatal "chain-fragment: missing $node_dir/db (not a single-node/solo run?)"
    test -f "$node_dir/config.json"                    || fatal "chain-fragment: missing $node_dir/config.json"
    test -f "$run_dir/profile.json"                    || fatal "chain-fragment: missing $run_dir/profile.json"
    test -e "$genesis_dir/genesis.shelley.json.orig"   || fatal "chain-fragment: missing $genesis_dir/genesis.shelley.json.orig"

    local profile_name=$(jq -r '.name' "$run_dir"/profile.json)
    test -n "$profile_name" -a "$profile_name" != null || fatal "chain-fragment: could not read profile name from $run_dir/profile.json"

    local beacon_chain_dir="$consensus_tools_dir"/beacon-data/chain
    local dest_dir="$beacon_chain_dir"/"$profile_name"
    local register_file="$beacon_chain_dir"/chain-register.json

    test -d "$beacon_chain_dir" || fatal "chain-fragment: not found: $beacon_chain_dir (wrong CONSENSUS-TOOLS-DIR?)"
    test -f "$register_file"    || fatal "chain-fragment: not found: $register_file"

    if test -e "$dest_dir" -a -z "$force"
    then fatal "chain-fragment: $dest_dir already exists; pass --force to overwrite"
    fi

    progress "chain-fragment" "exporting profile $(with_color yellow "$profile_name") from run $(with_color white "$run_tag")"
    progress "chain-fragment" "-> $dest_dir"

    rm -rf "$dest_dir"
    mkdir -p "$dest_dir"

    cp -R "$node_dir"/db "$dest_dir"/db

    local era
    for era in alonzo byron conway dijkstra
    do cp "$genesis_dir"/genesis.$era.json "$dest_dir"/genesis.$era.json
    done
    ## The node ran with a trimmed shelley genesis; the beacon chain needs the
    ## full, untrimmed one it was trimmed from.
    cp -L "$genesis_dir"/genesis.shelley.json.orig "$dest_dir"/genesis.shelley.json

    jq '
      (.AlonzoGenesisFile, .ByronGenesisFile, .ConwayGenesisFile, .DijkstraGenesisFile, .ShelleyGenesisFile)
        |= ("./" + (. / "/" | last))
    ' "$node_dir"/config.json > "$dest_dir"/config.json

    jq_fmutate "$register_file" \
        --arg name "$profile_name" \
        --arg desc "Generated by $profile_name profile" \
        '.[$name] = { chHomeDir: $name, chDbDir: "db", chConfigFile: "config.json", chDescription: $desc }'

    progress "chain-fragment" "done"
    msg "note: chain-register.json entry for '$profile_name' has no chFromSlot set; refine it by hand once you've picked a representative starting slot."
    ;;

* ) usage_chain_fragment;; esac
}
