#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

shellcheck --version > /dev/null 2>&1 || {
    echo "Missing 'shellcheck' executable."
    exit 1
}

error=0

shellcheck test/cli/core/common
fail_on_error $?

files=$(find test/cli -name run)
for file in ${files} ; do
  shellcheck "${file}"
  fail_on_error $?
  done

report_result ${error}
