#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

OUTPUT_DIR="${TEST}"

rm -rf "${OUTPUT_DIR}"
mkdir "${OUTPUT_DIR}"

error=0

${CARDANO_CLI} shelley node key-gen \
    --verification-key-file "${OUTPUT_DIR}/key-gen.vkey" \
    --signing-key-file "${OUTPUT_DIR}/key-gen.skey" \
    --operational-certificate-issue-counter "${OUTPUT_DIR}/op-cert.counter"

assert_file_exists "${OUTPUT_DIR}/key-gen.vkey"
assert_file_exists "${OUTPUT_DIR}/key-gen.skey"
assert_file_exists "${OUTPUT_DIR}/op-cert.counter"

assert_string 'Node operator verification key' "${OUTPUT_DIR}/key-gen.vkey"
assert_string 'Node operator signing key' "${OUTPUT_DIR}/key-gen.skey"
assert_string 'Node operational certificate issue counter' "${OUTPUT_DIR}/op-cert.counter"

report_result ${error}
