#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

${CARDANO_CLI} shelley node key-gen \
    --verification-key-file "${TEST_DIR}/key-gen.vkey" \
    --signing-key-file "${TEST_DIR}/key-gen.skey" \
    --operational-certificate-issue-counter "${TEST_DIR}/op-cert.counter"

assert_file_exists "${TEST_DIR}/key-gen.vkey"
assert_file_exists "${TEST_DIR}/key-gen.skey"
assert_file_exists "${TEST_DIR}/op-cert.counter"

assert_string 'StakePoolVerificationKey_ed25519' "${TEST_DIR}/key-gen.vkey"
assert_string 'StakePoolSigningKey_ed25519' "${TEST_DIR}/key-gen.skey"
assert_string 'NodeOperationalCertificateIssueCounter' "${TEST_DIR}/op-cert.counter"

report_result ${error}
