#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

# Use the same (faked) TxIn for both transactions.
tx_in="2392d2b1200b5139fe555c81261697b29a8ccf561c5c783d46e78a479d977053#0"

#-----------------------------
# Using a Byron output address

out_address=$(head -1 "test/cli/${testname}/data/byron-hex.address")
tx_out="${out_address}+100"

${CARDANO_CLI} shelley transaction build-raw \
    --tx-in "${tx_in}" \
    --tx-out "${tx_out}"  \
    --ttl 60 \
    --fee 12 \
    --tx-body-file "${TEST_DIR}/tx-body-out"
fail_on_error $?

# cat "${TEST_DIR}/tx-body-out"

#-----------------------------
# Using a Shelley output address
out_address=$(head -1 "test/cli/${testname}/data/shelley-hex.address")
tx_out="${out_address}+100"

${CARDANO_CLI} shelley transaction build-raw \
    --tx-in "${tx_in}" \
    --tx-out "${tx_out}"  \
    --ttl 60 \
    --fee 12 \
    --tx-body-file "${TEST_DIR}/tx-body-out"
fail_on_error $?

assert_file_exists "${TEST_DIR}/tx-body-out"
assert_string 'TxUnsignedShelley' "${TEST_DIR}/tx-body-out"

#-----------------------------

report_result ${error}
