#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

if test -d cardano-cli ; then
  cd cardano-cli || exit 1
  fi

OUTPUT_DIR="${TEST}"

rm -rf "${OUTPUT_DIR}"
if test -d cardano-cli ; then
  cd cardano-cli || exit 1
  fi

mkdir "${OUTPUT_DIR}"

error=0

# Use the same (faked) TxIn for both transactions.
tx_in="2392d2b1200b5139fe555c81261697b29a8ccf561c5c783d46e78a479d977053#0"

#-----------------------------
# Using a Byron output address

# Currently this gives:
# FatalError {fatalErrorMessage = "TODO: toShelleyTxOut convert byron address to Shelley bootstrap address"}
# The code to convert a Byron address is not done yet.

# out_address=$(head -1 "test/cli/${testname}/data/byron-hex.address")
# tx_out="${out_address}\$100"
#
# ${CARDANO_CLI} shelley transaction build-raw \
#     --tx-in ${tx_in} \
#     --tx-out ${tx_out}  \
#     --ttl 60 \
#     --fee 12 \
#     --tx-body-file "${OUTPUT_DIR}/tx-body-out"
# fail_on_error $?
#
# cat "${OUTPUT_DIR}/tx-body-out"

#-----------------------------
# Using a Shelley output address
out_address=$(head -1 "test/cli/${testname}/data/shelley-hex.address")
tx_out="${out_address}+100"

${CARDANO_CLI} shelley transaction build-raw \
    --tx-in "${tx_in}" \
    --tx-out "${tx_out}"  \
    --ttl 60 \
    --fee 12 \
    --tx-body-file "${OUTPUT_DIR}/tx-body-out"
fail_on_error $?

assert_file_exists "${OUTPUT_DIR}/tx-body-out"
assert_string 'TxUnsignedShelley' "${OUTPUT_DIR}/tx-body-out"

#-----------------------------

report_result ${error}
