#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

setup_data_dir "${testname}"
assert_file_exists "${DATA_DIR}/genesis.vkey"

${CARDANO_CLI} shelley genesis key-hash \
    --verification-key-file "${DATA_DIR}/genesis.vkey" \
    > "${TEST_DIR}/genesis-vkey-hash"

assert_file_exists "${TEST_DIR}/genesis-vkey-hash"
assert_line_count 1 "${TEST_DIR}/genesis-vkey-hash"
assert_string "f1b1b8fa2787aeaada49d4c852c57a552b43d0efc664bde22cd64286" "${TEST_DIR}/genesis-vkey-hash"

report_result ${error}
