#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

# Defaults to signing a Mainnet transaction.
${CARDANO_CLI} shelley text-view decode-cbor \
    --file "test/cli/${testname}/data/unsigned.tx" \
    > "${TEST_DIR}/decoded.txt"
fail_on_error $?

assert_file_exists "${TEST_DIR}/decoded.txt"

line_count=$(wc -l < "${TEST_DIR}/decoded.txt")
if test "${line_count}" -lt 10 ; then
  echo "Error: Expected at least 10 lines"
  cat "${TEST_DIR}/decoded.txt"
  error=1
  fi

assert_string '# int(4999998000)' "${TEST_DIR}/decoded.txt"
assert_string '# int(2000)' "${TEST_DIR}/decoded.txt"
assert_string '# int(1000)' "${TEST_DIR}/decoded.txt"

report_result ${error}
