#!/bin/sh
# This script validates the staged changes in Haskell files using stylish-haskell and hlint and returns non-zero
# code when there are linting or style issues.
#
# To set this script as your pre-commit hook, use the following command:
#
# ln -s $(git-root)/scripts/githooks/haskell-style-lint $(git rev-parse --git-dir)/hooks/pre-commit
#

for x in $(git diff --staged --name-only --diff-filter=ACM | tr '\n' ' '); do
  if [ "${x##*.}" = "hs" ]; then
    if grep -qE '^#' "$x"; then
      echo "$x contains CPP.  Skipping."
    else
      stylish-haskell -i "$x"
    fi
    # fail on linting issues
    hlint "$x"
  fi
done

# fail if there are style issues
git --no-pager diff --exit-code
