# global filter; messages must have at least this severity to pass:
minSeverity: Debug

# global file rotation settings:
rotation:
  rpLogLimitBytes: 5000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK
  - kind: TraceAcceptorBK
    path: logs/log-pipe-0
  - kind: TraceAcceptorBK
    path: logs/log-pipe-1
  - kind: TraceAcceptorBK
    path: logs/log-pipe-2

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK
  - kind: TraceAcceptorBK
    path: logs/log-pipe-0
  - kind: TraceAcceptorBK
    path: logs/log-pipe-1
  - kind: TraceAcceptorBK
    path: logs/log-pipe-2

# if wanted, the GUI is listening on this port:
#hasGUI: 12872

# if wanted, the EKG interface is listening on this port:
#hasEKG: 12782

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: StdoutSK
    scName: stdout
    scFormat: ScText
    scRotation: null
  - scKind: FileSK
    scFormat: ScText
    scName: "logs/acceptor.log"
    scRotation:
      rpLogLimitBytes: 25000000
      rpKeepFilesNum:  3
      rpMaxAgeHours:   24

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - StdoutSK
    - stdout
  - - FileSK
    - "logs/acceptor.log"

# more options which can be passed as key-value pairs:
options:
  cfokey:
    value: "Release-1.0.0"
  mapSubtrace:
    '#ekgview':
      contents:
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: .monoclock.basic.
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.cpuNs.timed.
      - - tag: StartsWith
          contents: '#ekgview.#aggregation.cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.gcNum.timed.
      subtrace: FilterTrace
    'cardano.epoch-validation.utxo-stats':
      # Change the `subtrace` value to `Neutral` in order to log
      # `UTxO`-related messages during epoch validation.
      subtrace: NoTrace
    '#messagecounters.aggregation':
      subtrace: NoTrace
    'cardano.#messagecounters.aggregation':
      subtrace: NoTrace
    '#messagecounters.ekgview':
      subtrace: NoTrace
    'cardano.#messagecounters.ekgview':
      subtrace: NoTrace
    '#messagecounters.switchboard':
      subtrace: NoTrace
    'cardano.#messagecounters.switchboard':
      subtrace: NoTrace
    '#messagecounters.katip':
      subtrace: NoTrace
    'cardano.#messagecounters.katip':
      subtrace: NoTrace
    '#messagecounters.monitoring':
      subtrace: NoTrace
    'cardano.#messagecounters.monitoring':
      subtrace: NoTrace
  mapBackends:
    cardano.epoch-validation.benchmark:
      - AggregationBK
    '#aggregation.cardano.epoch-validation.benchmark':
      - EKGViewBK

##########################################################
############### Cardano Node Configuration ###############
##########################################################


NodeId: 4
NodeHostAddress: ''
NodePort: 7000
Protocol: RealPBFT
GenesisHash: 5f20df933584822601f9e3f8c024eb5eb252fe8cefb24d1317dc3d432e940ebb
NumCoreNodes: 1
RequiresNetworkMagic: RequiresNoMagic
PBftSignatureThreshold: 0.5
TurnOnLogging: True
ViewMode: SimpleView
TurnOnLogMetrics: False

##### Network Time Parameters #####

ResponseTimeout: 30000000
PollDelay: 1800000000
Servers: [ "0.pool.ntp.org"
         , "2.pool.ntp.org"
         , "3.pool.ntp.org"
         ]

#####    Update Parameters    #####

ApplicationName: cardano-sl
ApplicationVersion: 1
LastKnownBlockVersion-Major: 0
LastKnownBlockVersion-Minor: 2
LastKnownBlockVersion-Alt: 0

MemPoolLimitTx: 200
AssetLockedSrcAddress: []

CacheParameter: 500
MessageCacheTimeout: 30

NetworkDiameter: 18
RecoveryHeadersMessage: 2200
StreamWindow: 2048
NonCriticalCQBootstrap: 0.95
NonCriticalCQ: 0.8
CriticalCQBootstrap: 0.8888
CriticalCQ: 0.654321
CriticalForkThreshold: 3
FixedTimeCQ: 3600

SlotLength: 20000
NetworkConnectionTimeout: 15000
HandshakeTimeout: 30000

#####       Certificates       #####


CA-Organization: "Input Output HK"
CA-CommonName: "Cardano SL Self-Signed Root CA"
CA-ExpiryDays: 3600
CA-AltDNS: []

Server-Organization: "Input Output HK"
Server-CommonName: "Cardano SL Server"
Server-ExpiryDays: 3600
Server-AltDNS: [ "localhost"
               , "localhost.localdomain"
               , "127.0.0.1"
               , "::1"
               ]

Wallet-Organization: "Input Output HK"
Wallet-CommonName: "Daedalus Wallet"
Wallet-ExpiryDays: 3600
Wallet-AltDNS: []

Enabled: False
Rate: 0
Period: ''
Burst: 0
