#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

${CARDANO_CLI} shelley address key-gen \
    --verification-key-file "${TEST_DIR}/address.vkey" \
    --signing-key-file "${TEST_DIR}/address.skey"

assert_file_exists "${TEST_DIR}/address.vkey"
assert_file_exists "${TEST_DIR}/address.skey"

assert_string 'VerificationKeyShelley' "${TEST_DIR}/address.vkey"
assert_string 'SigningKeyShelley' "${TEST_DIR}/address.skey"

report_result ${error}
