#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

OUTPUT_DIR="${TEST}"

rm -rf "${OUTPUT_DIR}"
mkdir "${OUTPUT_DIR}"

error=0

${CARDANO_CLI} shelley address key-gen \
    --verification-key-file "${OUTPUT_DIR}/address.vkey" \
    --signing-key-file "${OUTPUT_DIR}/address.skey"

assert_file_exists "${OUTPUT_DIR}/address.vkey"
assert_file_exists "${OUTPUT_DIR}/address.skey"

count=$(grep -c VerificationKeyShelley "${OUTPUT_DIR}/address.vkey")
if test "${count}" != 1 ; then
  echo "${OUTPUT_DIR}/address.vkey: Expected VerificationKeyShelley"
  error=1
  fi

count=$(grep -c SigningKeyShelley "${OUTPUT_DIR}/address.skey")
if test "${count}" != 1 ; then
  echo "${OUTPUT_DIR}/address.skey: Expected SigningKeyShelley"
  error=1
  fi

report_result ${error}
