#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

if test -d cardano-cli ; then
  cd cardano-cli || exit 1
  fi

OUTPUT_DIR="${TEST}"

rm -rf "${OUTPUT_DIR}"
mkdir "${OUTPUT_DIR}"

DATA_DIR="test/cli/${testname}/data"
if test -d cardano-cli ; then
  DATA_DIR="cardano-cli/${DATA_DIR}"
  fi

error=0

${CARDANO_CLI} shelley stake-address registration-certificate  \
    --verification-key-file "${DATA_DIR}/key-gen-staking.vkey" \
    --out-file "${OUTPUT_DIR}/registration.cert"
fail_on_error $?

assert_file_exists "${OUTPUT_DIR}/registration.cert"
assert_string 'DelegationCertificateShelley' "${OUTPUT_DIR}/registration.cert"

#-----------------------------

report_result ${error}
