#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

setup_data_dir "${testname}"

error=0

${CARDANO_CLI} shelley stake-address registration-certificate  \
    --staking-verification-key-file "${DATA_DIR}/key-gen-staking.vkey" \
    --out-file "${TEST_DIR}/registration.cert"
fail_on_error $?

assert_file_exists "${TEST_DIR}/registration.cert"
assert_string 'Stake Address Registration Certificate' "${TEST_DIR}/registration.cert"

report_result ${error}
