#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

setup_data_dir "${testname}"

error=0

# Defaults to signing a Mainnet transaction.
${CARDANO_CLI} shelley transaction sign \
    --mainnet \
    --tx-body-file "${DATA_DIR}/tx-body-file" \
    --signing-key-file "${DATA_DIR}/initial-utxo1.skey" \
    --tx-file "${TEST_DIR}/signed.tx"
fail_on_error $?

assert_file_exists "${TEST_DIR}/signed.tx"
assert_string 'TxSignedShelley' "${TEST_DIR}/signed.tx"

# Sign for a testnet with a testnet network magic of 11, but use two signing keys.
${CARDANO_CLI} shelley transaction sign \
    --testnet-magic 11 \
    --tx-body-file "${DATA_DIR}/tx-body-file" \
    --signing-key-file "${DATA_DIR}/initial-utxo1.skey" \
    --signing-key-file "${DATA_DIR}/initial-utxo2.skey" \
    --tx-file "${TEST_DIR}/signed.tx"
fail_on_error $?

assert_file_exists "${TEST_DIR}/signed.tx"
assert_string 'TxSignedShelley' "${TEST_DIR}/signed.tx"

# Sign a pool registration transaction.
#TODO: This needs to use an unsigned tx with a registration certificate
${CARDANO_CLI} shelley transaction sign \
    --mainnet \
    --tx-body-file "${DATA_DIR}/tx-body-file" \
    --signing-key-file "${DATA_DIR}/utxo.skey" \
    --signing-key-file "${DATA_DIR}/stake.skey" \
    --signing-key-file "${DATA_DIR}/node-cold.skey" \
    --tx-file "${TEST_DIR}/tx-pool-reg.signed"
fail_on_error $?

assert_file_exists "${TEST_DIR}/signed.tx"
assert_string 'TxSignedShelley' "${TEST_DIR}/signed.tx"

report_result ${error}
