#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

${CARDANO_CLI} shelley node key-gen-staking \
    --verification-key-file "${TEST_DIR}/key-gen-staking.vkey" \
    --signing-key-file "${TEST_DIR}/key-gen-staking.skey"

assert_file_exists "${TEST_DIR}/key-gen-staking.vkey"
assert_file_exists "${TEST_DIR}/key-gen-staking.skey"

assert_string 'VerificationKeyStakingShelley' "${TEST_DIR}/key-gen-staking.vkey"
assert_string 'SigningKeyShelley' "${TEST_DIR}/key-gen-staking.skey"

report_result ${error}
