#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

OUTPUT_DIR="${TEST}"

rm -rf "${OUTPUT_DIR}"
mkdir "${OUTPUT_DIR}"

error=0

${CARDANO_CLI} shelley node key-gen-staking \
    --verification-key-file "${OUTPUT_DIR}/key-gen-staking.vkey" \
    --signing-key-file "${OUTPUT_DIR}/key-gen-staking.skey"

assert_file_exists "${OUTPUT_DIR}/key-gen-staking.vkey"
assert_file_exists "${OUTPUT_DIR}/key-gen-staking.skey"

assert_string 'VerificationKeyStakingShelley' "${OUTPUT_DIR}/key-gen-staking.vkey"
assert_string 'SigningKeyShelley' "${OUTPUT_DIR}/key-gen-staking.skey"

report_result ${error}
