# global filter; messages must have at least this severity to pass:
minSeverity: Notice

# global file rotation settings:
rotation:
  rpLogLimitBytes: 50000000
  rpKeepFilesNum:  100
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: FileSK
    scName: "node-0.json"
    scFormat: ScJson

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - FileSK
    - "node-0.json"

# more options which can be passed as key-value pairs:
options:
  cfokey:
    value: "Release-1.0.0"
  mapSubtrace:
    benchmark:
      contents:
        - GhcRtsStats
        - MonotonicClock
      subtrace: ObservableTrace
    '#ekgview':
      contents:
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: .monoclock.basic.
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.cpuNs.timed.
      - - tag: StartsWith
          contents: '#ekgview.#aggregation.cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.gcNum.timed.
      subtrace: FilterTrace
    'cardano.epoch-validation.utxo-stats':
      # Change the `subtrace` value to `Neutral` in order to log
      # `UTxO`-related messages during epoch validation.
      subtrace: NoTrace
    cardano.node-metrics:
      subtrace: Neutral
  mapBackends:
    cardano.epoch-validation.benchmark:
      - AggregationBK
    'cardano.node.peers.BlockFetchDecision':
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    'cardano.node.ChainDB':
      - KatipBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.metrics:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
##########################################################
############### Cardano Node Configuration ###############
##########################################################


NodeId:
Protocol: RealPBFT
NumCoreNodes: 1
RequiresNetworkMagic: RequiresNoMagic
PBftSignatureThreshold: 0.5
TurnOnLogging: True
ViewMode: SimpleView
TurnOnLogMetrics: True


#####    Update Parameters    #####

ApplicationName: cardano-sl
ApplicationVersion: 1
LastKnownBlockVersion-Major: 0
LastKnownBlockVersion-Minor: 2
LastKnownBlockVersion-Alt: 0
