#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

error=0

${CARDANO_CLI} shelley node key-gen-KES \
    --verification-key-file "${TEST_DIR}/kes.vkey" \
    --signing-key-file "${TEST_DIR}/kes.skey"

assert_file_exists "${TEST_DIR}/kes.vkey"
assert_file_exists "${TEST_DIR}/kes.skey"

assert_string 'KesVerificationKey_ed25519_kes_2^6' "${TEST_DIR}/kes.vkey"
assert_string 'KesSigningKey_ed25519_kes_2^6' "${TEST_DIR}/kes.skey"

report_result ${error}
