name: Actionlint

on:
  merge_group:
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      # We want to install Nix to provision shellcheck, so that actionlint doesn't install
      # its own shellcheck. This will also make sure that this pipeline runs using
      # the same shellcheck as the ones in Nix shells of developers.
      - name: Install Nix
        uses: cachix/install-nix-action@b97f05dcb019ddea06450a50ef6203d2fdc19fee # v31
        with:
          extra_nix_config: |
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io/
      # Make the Nix environment available to next steps
      - uses: rrbutani/use-nix-shell-action@f97339023a09121113e5a58ad88fe0e9fde3406b # v1

      - name: actionlint
        run: |
          for file in $(git ls-files ".github/workflows/*.y*ml")
          do
            if grep -q "$file" ".github/workflows/actionlint-exceptions.txt"
            then
              echo "⚠️ $file is ignored from actionlint's verifications. Please consider fixing it."
            else
              echo "actionlint $file"
              actionlint "$file"
            fi
          done
