name: Check testnet manifest schema

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  check-testnet-manifest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Install Nix
      uses: cachix/install-nix-action@b97f05dcb019ddea06450a50ef6203d2fdc19fee # v31
      with:
        nix_path: nixpkgs=channel:nixos-24.05
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          experimental-features = nix-command flakes
          allow-import-from-derivation = true
          extra-substituters = https://cache.iog.io/
          extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        persist-credentials: false

    - name: Validate cardano-testnet manifest golden file against its schema
      run: make testnet-manifest-validate
