name: Changelog check for cardano-testnet

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  check-scriv-cardano-testnet:
    name: Check for scriv fragment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Check for changes in cardano-testnet
        uses: dorny/paths-filter@6852f92c20ea7fd3b0c25de3b5112db3a98da050 # v3
        id: filter
        with:
          filters: |
            cardano:
              - 'cardano-testnet/**'

      - name: Check for changelog changes
        if: steps.filter.outputs.cardano == 'true'
        uses: brettcannon/check-for-changed-files@871d7b8b5917a4f6f06662e2262e8ffc51dff6d1 # v1
        with:
          file-pattern: "cardano-testnet/changelog.d/*.md"
          skip-label: "no-changelog-needed"
          failure-message: "You modified `cardano-testnet` but are missing a changelog fragment! Please run `scriv create` or apply the `no-changelog-needed` label."

      - name: Install Nix
        if: steps.filter.outputs.cardano == 'true'
        uses: cachix/install-nix-action@b97f05dcb019ddea06450a50ef6203d2fdc19fee # v31
        with:
          extra_nix_config: |
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io/

      - uses: rrbutani/use-nix-shell-action@v1
        if: steps.filter.outputs.cardano == 'true'
        with:
          flakes: nixpkgs#scriv
      - name: Check scriv fragments are correct
        if: steps.filter.outputs.cardano == 'true'
        run: cd cardano-testnet && scriv collect --version "CI-CHECK" --keep

