name: "Haddock documentation"

on:
  workflow_dispatch:
  pull_request: # TODO: remove
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v6

    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          accept-flake-config = true
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    # GHC 9.14 avoids the tyConStupidTheta panic in GHC 9.6 haddock
    - uses: rrbutani/use-nix-shell-action@v1
      with:
        devShell: .#ghc914

    - name: Update cabal indices
      run: |
        cabal update

    - name: Build whole project
      run: |
        cabal build all

    - name: Build documentation
      run: |
        cabal haddock-project --local --output=./haddocks --internal --foreign-libraries

    - name: Compress haddocks
      run: |
        tar -czf haddocks.tgz -C haddocks .

    - name: Upload haddocks artifact
      uses: actions/upload-artifact@v7
      if: ${{ always() }}
      continue-on-error: true
      with:
        name: haddocks
        path: ./haddocks.tgz

    - name: Upload cabal logs
      uses: actions/upload-artifact@v7
      if: failure()
      continue-on-error: true
      with:
        name: cabal-haddock-logs
        path: ~/.cache/cabal/logs/

    - name: Deploy documentation to gh-pages 🚀
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN || github.token }}
        publish_dir: haddocks
        cname: cardano-node.cardano.intersectmbo.org
        force_orphan: true
