name: "Haddock documentation"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@b97f05dcb019ddea06450a50ef6203d2fdc19fee # v31
      with:
        # Use last stable nixos channel and the same nix as in channel:
        nix_path: nixpkgs=channel:nixos-24.05
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          experimental-features = nix-command flakes
          allow-import-from-derivation = true
          extra-substituters = https://cache.iog.io/
          extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false

    - name: Fetch nix cache and update cabal indices
      run: |
        nix develop --command \
          cabal update

    - name: Build whole project
      run: |
        nix develop --command \
          cabal build all

    - name: Build documentation
      run: |
        nix develop --command \
          cabal haddock-project --local --output=./haddocks --internal --foreign-libraries

    - name: Compress haddocks
      run: |
        tar -czf haddocks.tgz -C haddocks .

    - name: Upload haddocks artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      if: ${{ always() }}
      continue-on-error: true
      with:
        name: haddocks
        path: ./haddocks.tgz

    - name: Deploy documentation to gh-pages 🚀
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@e9c66a37f080288a11235e32cbe2dc5fb3a679cc # v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN || github.token }}
        publish_dir: haddocks
        cname: cardano-node.cardano.intersectmbo.org
        force_orphan: true
