name: Check Markdown links

on:
  pull_request: # Required for workflows to be able to be approved from forks
  merge_group:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
    - uses: tcort/github-action-markdown-link-check@e7c7a18363c842693fadde5d41a3bd3573a7a225 # v1
      with:
        use-quiet-mode: yes
        config-file: '.github/mlc_config.json'
