#!/bin/sh -u

cwd=$(dirname "$0")

# shellcheck source=/dev/null
. "${cwd}/../core/common"

# shellcheck disable=SC2154
banner "${testname}"

DATA_DIR="test/cli/${testname}/data"
if test -d cardano-cli ; then
  DATA_DIR="cardano-cli/${DATA_DIR}"
  fi

error=0

#-------------------------

byron_base58=$(head -1 "${DATA_DIR}/byron-base58.address")

${CARDANO_CLI} shelley address info \
    --address "${byron_base58}" \
    > "${TEST_DIR}/describe"

assert_file_exists "${TEST_DIR}/describe"
assert_string 'Encoding: Base58' "${TEST_DIR}/describe"
assert_string 'Era: Byron' "${TEST_DIR}/describe"

#-------------------------

byron_hex=$(head -1 "${DATA_DIR}/byron-hex.address")

${CARDANO_CLI} shelley address info \
    --address "${byron_hex}" \
    > "${TEST_DIR}/describe"

assert_file_exists "${TEST_DIR}/describe"
assert_string 'Encoding: Hex' "${TEST_DIR}/describe"
assert_string 'Era: Byron' "${TEST_DIR}/describe"

#-------------------------

shelley_hex=$(head -1 "${DATA_DIR}/shelley-hex.address")

${CARDANO_CLI} shelley address info \
    --address "${shelley_hex}" \
    > "${TEST_DIR}/describe"

assert_file_exists "${TEST_DIR}/describe"
assert_string 'Encoding: Hex' "${TEST_DIR}/describe"
assert_string 'Era: Shelley' "${TEST_DIR}/describe"

#-------------------------

report_result ${error}
